// Session materials read helper (S-06).
//
// Loads the metadata rows for a session's uploaded file(s). The signed download
// URL is generated by the caller (the detail page) from `storage_path` so this
// helper stays a pure DB read and is testable through the RLS harness. RLS scopes
// the read to the owner; the explicit session filter is defense-in-depth.

import type { SupabaseClient } from "@supabase/supabase-js";

import type { Database } from "@/db/database.types";
import type { Material } from "@/types";

/** The columns the history detail view needs per uploaded file. */
export type SessionMaterial = Pick<Material, "id" | "filename" | "mime_type" | "size_bytes" | "storage_path">;

/**
 * The session's uploaded file metadata, oldest first. Returns [] when there are
 * none (or on read error — the detail page degrades to "no files" rather than failing).
 */
export async function loadSessionMaterials(
  supabase: SupabaseClient<Database>,
  sessionId: string,
): Promise<SessionMaterial[]> {
  const { data, error } = await supabase
    .from("materials")
    .select("id, filename, mime_type, size_bytes, storage_path")
    .eq("session_id", sessionId)
    .order("created_at");

  if (error) {
    console.error("[history] loadSessionMaterials failed:", error.message);
    return [];
  }
  return data;
}
